connection: &connection
  username: postgres
  password: postgres
  adapter: postgresql
  encoding: utf8
  host: localhost
  min_messages: WARNING

development:
  database: copycopter_development
  <<: *connection

test:
  database: copycopter_test
  <<: *connection
